name: bloc_utils
description: "Bloc utils by dipflix"
version: 0.0.1

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

